### ISSUE TITLE
Error on django ImageField

### ISSUE THREAD

**Issue by 50Bytes-dev** [jordaneremieff/djantic#31]
Error if I add in scheme field _avatar_

**Model:**
```
def get_avatar_upload_path(instance, filename):
    return os.path.join(
        "customer_avatar", str(instance.id), filename)


class Customer(models.Model):
    """
    params: user* avatar shop* balance permissions deleted

    prefetch: -
    """
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customers', verbose_name='Пользователь')
    avatar = models.ImageField(upload_to=get_avatar_upload_path, verbose_name='Аватарка', blank=True, null=True)
    retail = models.ForeignKey('retail.Retail', on_delete=models.CASCADE, related_name='customers', verbose_name='Розница')
    balance = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Баланс', default=0)
    permissions = models.ManyToManyField('retail.Permission', verbose_name='Права доступа', related_name='customers', blank=True)
    deleted = models.BooleanField(default=False, verbose_name='Удален')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
```

**Scheme**
```
class CustomerSchema(ModelSchema):
    user: UserSchema

    class Config:
        model = Customer
        include = ['id', 'user', 'avatar', 'retail', 'balance', 'permissions']
```

**Error:**
```
fastapi_1  | Process SpawnProcess-36:
fastapi_1  | Traceback (most recent call last):
fastapi_1  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
fastapi_1  |     self.run()
fastapi_1  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
fastapi_1  |     self._target(*self._args, **self._kwargs)
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
fastapi_1  |     target(sockets=sockets)
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
fastapi_1  |     loop.run_until_complete(self.serve(sockets=sockets))
fastapi_1  |   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 397, in serve
fastapi_1  |     config.load()
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
fastapi_1  |     self.loaded_app = import_from_string(self.app)
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
fastapi_1  |     module = importlib.import_module(module_str)
fastapi_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
fastapi_1  |     return _bootstrap._gcd_import(name[level:], package, level)
fastapi_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
fastapi_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
fastapi_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
fastapi_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
fastapi_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
fastapi_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
fastapi_1  |   File "/opt/project/config/asgi.py", line 18, in <module>
fastapi_1  |     from backend.retail.fastapp import app
fastapi_1  |   File "/opt/project/backend/retail/fastapp.py", line 9, in <module>
fastapi_1  |     from backend.retail.routers import router
fastapi_1  |   File "/opt/project/backend/retail/routers.py", line 3, in <module>
fastapi_1  |     from backend.retail.api import auth, postitem, ping, customer
fastapi_1  |   File "/opt/project/backend/retail/api/customer.py", line 8, in <module>
fastapi_1  |     from backend.retail.schemas.customer import CustomerSchema
fastapi_1  |   File "/opt/project/backend/retail/schemas/customer.py", line 7, in <module>
fastapi_1  |     class CustomerSchema(ModelSchema):
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/djantic/main.py", line 97, in __new__
fastapi_1  |     python_type, pydantic_field = ModelSchemaField(field)
fastapi_1  |   File "/usr/local/lib/python3.8/site-packages/djantic/fields.py", line 135, in ModelSchemaField
fastapi_1  |     python_type,
fastapi_1  | UnboundLocalError: local variable 'python_type' referenced before assignment
```

**Comment by spyker77** [comment]
The same type of error with the following configuration:

**Model**
```
class Vacancy(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.URLField(max_length=255, unique=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    rated_skills = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    search_vector = SearchVectorField(null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Vacancies"
        indexes = [GinIndex(fields=["search_vector"], name="search_vector_idx")]
```
        
**Schema**
```
class VacancySchema(ModelSchema):
    class Config:
        model = Vacancy
```

The error occurs even without any direct calls, just when trying to run docker containers.
Version used: **0.3.0** as this is the latest version available in PyPI.

**Comment by jordaneremieff** [comment]
Hi @50Bytes-dev @spyker77,

I've pushed a new release 0.3.2 with the most recent changes. Please confirm the issues persists using this new release, I'll take a look if it does not resolve things.

**Comment by spyker77** [comment]
Hi @jordaneremieff 👋
Nope, unfortunately, the error is still present:
```
Traceback (most recent call last):
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
api_1    |     worker.init_process()
api_1    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/workers.py", line 63, in init_process
api_1    |     super(UvicornWorker, self).init_process()
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
api_1    |     self.load_wsgi()
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
api_1    |     self.wsgi = self.app.wsgi()
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
api_1    |     self.callable = self.load()
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
api_1    |     return self.load_wsgiapp()
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
api_1    |     return util.import_app(self.app_uri)
api_1    |   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
api_1    |     mod = importlib.import_module(module)
api_1    |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
api_1    |     return _bootstrap._gcd_import(name[level:], package, level)
api_1    |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
api_1    |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
api_1    |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
api_1    |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
api_1    |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
api_1    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
api_1    |   File "/code/config/asgi.py", line 12, in <module>
api_1    |     from fast_api.main import create_application
api_1    |   File "/code/fast_api/main.py", line 7, in <module>
api_1    |     from fast_api.api.v1.routers import api_router_v1
api_1    |   File "/code/fast_api/api/v1/routers.py", line 3, in <module>
api_1    |     from .endpoints import skills
api_1    |   File "/code/fast_api/api/v1/endpoints/skills.py", line 7, in <module>
api_1    |     from fast_api.schemas import VacanciesSchema, VacancySchema
api_1    |   File "/code/fast_api/schemas.py", line 11, in <module>
api_1    |     class VacancySchema(ModelSchema):
api_1    |   File "/usr/local/lib/python3.9/site-packages/djantic/main.py", line 96, in __new__
api_1    |     python_type, pydantic_field = ModelSchemaField(field)
api_1    |   File "/usr/local/lib/python3.9/site-packages/djantic/fields.py", line 139, in ModelSchemaField
api_1    |     python_type,
api_1    | UnboundLocalError: local variable 'python_type' referenced before assignment
```

**Comment by jordaneremieff** [comment]
@spyker77 this is the result of the `SearchVectorField` specifically. I'm going to push a change to assume a default `python_type` in such cases and log a warning. 0.3.3 should be available in PyPi shortly.

If this field type requires special consideration then please open a new issue to discuss it's handling specifically, for now it will default to string.
